exports.HiraganaTable=[
    {font:'a', desc:'あ'},{font:'i', desc:'い'},
	{font:'u', desc:'う'},{font:'e', desc:'え'},
	{font:'o', desc:'お'},
	{font:'ka', desc:'か'},{font:'ki', desc:'き'},
	{font:'ku', desc:'く'},{font:'ke', desc:'け'},
	{font:'ko', desc:'こ'},
	{font:'ga', desc:'が'},{font:'gi', desc:'ぎ'},
	{font:'gu', desc:'ぐ'},{font:'ge', desc:'げ'},
	{font:'go', desc:'ご'},
	{font:'sa', desc:'さ'},{font:'shi', desc:'し'},
	{font:'su', desc:'す'},{font:'se', desc:'せ'},
	{font:'so', desc:'そ'},
	{font:'za', desc:'ざ'},{font:'ji', desc:'じ'},
	{font:'zu', desc:'ず'},{font:'ze', desc:'ぞ'},
	{font:'zo', desc:'ぞ'},
	{font:'ta', desc:'た'},{font:'chi', desc:'ち'},
	{font:'tsu', desc:'つ'},{font:'te', desc:'て'},
	{font:'to', desc:'と'},
	{font:'da', desc:'だ'}, {font:'ji', desc:'ぢ'},
	{font:'zu', desc:'づ'}, {font:'de', desc:'で'},
	{font:'do', desc:'ど'},
	{font:'na', desc:'な'}, {font:'ni', desc:'に'},
	{font:'nu', desc:'ぬ'}, {font:'ne', desc:'ね'},
	{font:'no', desc:'の'},
	{font:'ha', desc:'は'}, {font:'hi', desc:'ひ'}, 
	{font:'fu', desc:'ふ'}, {font:'he', desc:'へ'},
	{font:'ho', desc:'ほ'},
	{font:'ba', desc:'ば'}, {font:'bi', desc:'び'},
	{font:'bu', desc:'ぶ'}, {font:'be', desc:'べ'},
	{font:'bo', desc:'ぼ'}, 
	{font:'pa', desc:'ぱ'}, {font:'pi', desc:'ぴ'},
	{font:'pu', desc:'ぷ'}, {font:'pe', desc:'ぺ'},
	{font:'po', desc:'ぽ'},
	{font:'ma', desc:'ま'}, {font:'mi', desc:'み'},
	{font:'mu', desc:'む'}, {font:'me', desc:'め'},
	{font:'mo', desc:'も'},
	{font:'ya', desc:'や'}, {font:'yu', desc:'ゆ'},
	{font:'yo', desc:'よ'},
	{font:'ra', desc:'ら'}, {font:'ri', desc:'り'},
	{font:'ru', desc:'る'}, {font:'re', desc:'れ'},
	{font:'ro', desc:'ろ'},
	{font:'wa', desc:'わ'}, {font:'wo', desc:'を'},
	{font:'n', desc:'ん'}
];