exports.KatakanaTable=[
    {font:'a', desc:'ア'},  {font:'i', desc:'イ'},
    {font:'u', desc:'ウ'},  {font:'e', desc:'エ'},
    {font:'o', desc:'オ'},
    {font:'ka',desc:'カ'},  {font:'ki', desc:'キ'},
    {font:'ku',desc:'ク'},  {font:'ke', desc:'ケ'},
    {font:'ko',desc:'コ'},
    {font:'sa',desc:'サ'},  {font:'shi',desc:'シ'},
    {font:'su',desc:'ス'},  {font:'se', desc:'セ'},
    {font:'so',desc:'ソ'},
    {font:'na',desc:'ナ'},    {font:'ni', desc:'ニ'},
    {font:'nu',desc:'ヌ'},    {font:'ne', desc:'ネ'},
    {font:'no',desc:'ノ'},
    {font:'ha',desc:'ハ'},      {font:'hi', desc:'ヒ'},
    {font:'fu',desc:'フ'},    {font:'he', desc:'ヘ'},
    {font:'ho',desc:'ホ'},    
    {font:'ma',desc:'マ'},    {font:'mi',desc:'ミ'},
    {font:'mu',desc:'ム'},    {font:'me',desc:'メ'},
    {font:'mo',desc:'モ'}, 
    {font:'ya',desc:'ヤ'},    {font:'yu',desc:'ユ'},
    {font:'yo',desc:'ヨ'},
    {font:'ra',desc:'ラ'},    {font:'ri',desc:'リ'},
    {font:'ru',desc:'ル'},    {font:'re',desc:'レ'},
    {font:'ro',desc:'ロ'},
    {font:'wa',desc:'ワ'},    {font:'wo',desc:'ヲ'},
    {font:'n' ,desc:'ン'}   
];